name: 'SSH Remote Commands'
description: 'Executing remote ssh commands'
author: 'Abid Malik'
inputs:
  script:
    description: 'execute commands'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
